### ISSUE TITLE
Additions to the Map Screen

### ISSUE THREAD

**Issue by gaioc** [DannyLeWasTaken/CodingClubGame#2]
[Enhancement]
# The creation of a system to create new maps, and new tile types.
This would entail:

## Creating a file, tiles.txt in the mapScreen folder

This file could then be read in by a function which would return a dict of Tile objects.
The format of the file would be as follows:

```py
F
floor.png
True

W
wall.png
False
```

Each entry would have a one character identifier, a file name, and a bool determining collisions. (True is walkable, False is not)

## Creating a folder, maps, in the mapScreen folder.

This folder would hold multiple files that would have the following format.

```py
8 8

WWFWWWWW
WFFFFFFW
WFFFFFFW
WFFFFFFW
WFFFFFFW
WFFFFFFW
WFFFFFFW
WWFWWWWW

4 4 npc1

2 0 loadingzone1
2 7 loadingzone2
```

### Bonus: create a tool which allows level designers to quickly and easily create files in this format (map editor)

**Comment by DannyLeWasTaken** [comment]
A map editor seems overkill imo. Text works fine as is and defining extra data of each tile as you have is a great method. Wouldn't have thought of that myself.

**Comment by gaioc** [comment]
Assigning this to myself, going to at least finish tiles and map format and reading. Depending on how easy it’ll be to port over my old map editor, I might do that. I’ll link it in this thread if I do.

**Comment by gaioc** [comment]
Also, the loading zones will need a slightly different format than what I had initially proposed. My new proposition would work like this:

```py
2 0 loadingzone1 2 8
```
This would include the target destination on the next map.

**Comment by gaioc** [comment]
Finished this up in pull request #17 . Waiting for confirmation @DannyLeWasTaken, then we can close this.

**Comment by gaioc** [comment]
Issue has been fully completed.
